-- Create a table for storing leads
create table leads (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  company text not null,
  email text not null,
  phone text not null
);

-- Set up Row Level Security (RLS)
-- Enable RLS
alter table leads enable row level security;

-- Create a policy that allows anyone (anon) to insert data
create policy "Enable insert for everyone" on leads
  for insert
  with check (true);

-- Create a policy that allows only authenticated users (service role/dashboard) to view data
-- In this case, we might just want to allow no public select access, 
-- so we don't add a select policy for anon.
